version: '3.8'
services:
  {{ cookiecutter.repo_name }}:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    command: /bin/sh -c "while sleep 1000; do :; done"   
    volumes:
      - ~/.ssh:/home/user/.ssh
      - ..:/{{ cookiecutter.repo_name }}:cached
