version: '3.8'
services:
  {{ cookiecutter.repo_name }}:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile.gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ${PWD}:/{{ cookiecutter.repo_name }}:cached
    command: sleep infinity